#
# This file is auto-generated. DO NOT EDIT
# Generated by: autospec.py
#
Name     : bijiben
Version  : 40.1
Release  : 22
URL      : https://download.gnome.org/sources/bijiben/40/bijiben-40.1.tar.xz
Source0  : https://download.gnome.org/sources/bijiben/40/bijiben-40.1.tar.xz
Summary  : No detailed summary available
Group    : Development/Tools
License  : GPL-3.0
BuildRequires : buildreq-gnome
BuildRequires : buildreq-meson
BuildRequires : curl-dev
BuildRequires : gnome-online-accounts-dev
BuildRequires : pkgconfig(goa-1.0)
BuildRequires : pkgconfig(libcurl)
BuildRequires : pkgconfig(libecal-2.0)
BuildRequires : pkgconfig(libhandy-1)
BuildRequires : pkgconfig(webkit2gtk-4.0)
BuildRequires : tracker-dev
BuildRequires : webkitgtk-dev

%description
# GNOME Notes
GNOME Notes, formerly "Bijiben", is a note editor designed to remain simple to use.
(筆記本 / 笔记本 / bijiben means "notebook".)

%prep
%setup -q -n bijiben-40.1
cd %{_builddir}/bijiben-40.1

%build
export http_proxy=http://127.0.0.1:9/
export https_proxy=http://127.0.0.1:9/
export no_proxy=localhost,127.0.0.1,0.0.0.0
export LANG=C.UTF-8
export SOURCE_DATE_EPOCH=1642355735
export GCC_IGNORE_WERROR=1
export AR=gcc-ar
export RANLIB=gcc-ranlib
export NM=gcc-nm
export CFLAGS="$CFLAGS -O3 -ffat-lto-objects -flto=auto "
export FCFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export FFLAGS="$FFLAGS -O3 -ffat-lto-objects -flto=auto "
export CXXFLAGS="$CXXFLAGS -O3 -ffat-lto-objects -flto=auto "
CFLAGS="$CFLAGS" CXXFLAGS="$CXXFLAGS" LDFLAGS="$LDFLAGS" meson --libdir=lib64 --prefix=/usr --buildtype=plain   builddir
ninja -v -C builddir

%install
mkdir -p %{buildroot}/usr/share/package-licenses/bijiben
cp %{_builddir}/bijiben-40.1/COPYING %{buildroot}/usr/share/package-licenses/bijiben/338650eb7a42dd9bc1f1c6961420f2633b24932d
DESTDIR=%{buildroot} ninja -C builddir install

%files
%defattr(-,root,root,-)
